name: Build & Run Demo

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run demo build
        run: |
          echo "✅ Build & Run Demo workflow executed successfully"
