name: Python / Conda on Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: peects-env
          python-version: "3.10"
          auto-update-conda: true
          channels: conda-forge,defaults

      - name: Verify Conda Setup
        run: |
          conda info
          conda list

      - name: Install Python dependencies
        run: |
          conda install numpy pandas matplotlib -y
          pip install -r requirements.txt || echo "No requirements.txt found, skipping pip"

      - name: Run PEECTS tests (or main script)
        run: |
          echo "Running tests or main app"
          python -m unittest discover -s tests || echo "No tests found, skipping"
