name: Python / Conda on Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.10
        activate-environment: windows-env
        environment-file: environment.yml

    - name: Run Windows validation
      run: |
        echo "Running Conda-based validation on Windows..."
        python validate_windows.py

    - name: Upload validation logs
      uses: actions/upload-artifact@v4
      with:
        name: windows-validation-logs
        path: logs/

